# This is a basic workflow to help you get started with Actions

name: Update table of contents

# Controls when the workflow will run

# Never!
on: []

# Disabled by Doug Beatty on 2024-04-25 to fix CI
# https://github.com/dbt-labs/dbt-utils/issues/885
# on:
#   push:
#     branches: [main]
#     paths: ['README.md']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # actions/checkout@v3
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup README.md
          rm ./gh-md-toc
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a  # stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update table of contents
